# Generated by Django 2.2.3 on 2019-07-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_video_mp4file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('video', models.FileField(null=True, upload_to='allmedia/', verbose_name='')),
                ('audio', models.FileField(null=True, upload_to='allmedia/audio/', verbose_name='')),
                ('image', models.ImageField(default='', upload_to='pic_folder/')),
            ],
        ),
    ]
