# Generated by Django 2.2.3 on 2019-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190725_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('media_file', models.FileField(null=True, upload_to='videos/media_file/', verbose_name='')),
                ('file_types', models.CharField(choices=[('I', 'Image'), ('V', 'Video'), ('A', 'Audio')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
